"use client";
import { FormEvent, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Camera, CameraOff, Keyboard, QrCode } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
type Detection={rawValue:string}; type Detector=new(options:{formats:string[]})=>{detect(source:HTMLVideoElement):Promise<Detection[]>};
export default function QrScannerClientView(){const router=useRouter(),videoRef=useRef<HTMLVideoElement>(null),streamRef=useRef<MediaStream|null>(null),frameRef=useRef<number|null>(null);const[token,setToken]=useState(""),[active,setActive]=useState(false),[error,setError]=useState<string|null>(null);
 function navigate(value:string){const clean=value.trim();if(!clean)return;stop();router.push(`/qr/product/${encodeURIComponent(clean)}`)}function submit(e:FormEvent){e.preventDefault();navigate(token)}
 function stop(){if(frameRef.current)cancelAnimationFrame(frameRef.current);streamRef.current?.getTracks().forEach(track=>track.stop());streamRef.current=null;setActive(false)}useEffect(()=>()=>stop(),[]);
 async function start(){setError(null);const DetectorClass=(window as unknown as {BarcodeDetector?:Detector}).BarcodeDetector;if(!DetectorClass){setError("Live QR decoding is not supported by this browser. Use Chrome/Edge on HTTPS or paste the token manually.");return}try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});streamRef.current=stream;const video=videoRef.current;if(!video)return;video.srcObject=stream;await video.play();setActive(true);const detector=new DetectorClass({formats:["qr_code"]});const scan=async()=>{if(!streamRef.current)return;try{const results=await detector.detect(video);if(results[0]?.rawValue)return navigate(results[0].rawValue)}catch{}frameRef.current=requestAnimationFrame(()=>void scan())};void scan()}catch(e){setError(e instanceof Error?e.message:"Camera permission was denied.")}}
 return <main className="bg-[#F8FAFC] p-6 lg:p-8"><header><p className="text-sm font-semibold uppercase tracking-[.18em] text-[#0E9384]">Serialized product lookup</p><h1 className="mt-1 text-3xl font-bold">QR Scanner</h1><p className="mt-2 text-sm text-slate-500">Scan a TechNova serialized label or enter its opaque token manually.</p></header><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_380px]"><Card className="overflow-hidden"><div className="relative flex min-h-[460px] items-center justify-center bg-slate-950"><video ref={videoRef} muted playsInline className={`absolute inset-0 h-full w-full object-cover ${active?"block":"hidden"}`}/><div className="pointer-events-none absolute h-60 w-60 rounded-3xl border-2 border-[#2DD4BF] shadow-[0_0_0_9999px_rgba(0,0,0,.28)]"><span className="absolute left-3 right-3 top-1/2 h-0.5 bg-[#2DD4BF] shadow-[0_0_14px_#2DD4BF]"/></div>{!active&&<div className="text-center text-white"><Camera className="mx-auto h-9 w-9"/><p className="mt-3 font-semibold">Rear camera preview</p><p className="mt-1 text-xs text-white/60">Permission is requested only after you start scanning.</p></div>}</div><CardContent className="flex items-center justify-between p-4"><span className="text-sm text-slate-600">Align the complete QR label inside the frame.</span>{active?<Button onClick={stop} variant="outline"><CameraOff className="mr-2 h-4 w-4"/>Stop</Button>:<Button onClick={()=>void start()} className="bg-[#025148]"><Camera className="mr-2 h-4 w-4"/>Enable camera</Button>}</CardContent></Card><Card className="h-fit"><CardHeader><CardTitle className="flex items-center gap-2"><Keyboard className="h-5 w-5 text-[#0E9384]"/>Manual lookup</CardTitle></CardHeader><CardContent><form onSubmit={submit} className="space-y-4"><label className="space-y-2 text-sm font-medium">QR token<Input value={token} onChange={e=>setToken(e.target.value)} placeholder="Paste QR token" autoComplete="off"/></label><Button className="w-full bg-[#025148]" disabled={!token.trim()}><QrCode className="mr-2 h-4 w-4"/>View product details</Button></form>{error&&<p className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">{error}</p>}<div className="mt-5 rounded-xl bg-teal-50 p-4 text-sm text-teal-800"><b>Privacy:</b> public lookup exposes safe product, serial and warranty information only.</div></CardContent></Card></div></main>}
