import Link from "next/link";
import { serverApi } from "@/lib/api/server";

type ReturnDetail = { id: string; returnNumber: string; status: string; reason: string; resolution: string; total: string | number; storeCreditAmount: string | number; loyaltyPointsAwarded: number; createdAt: string; completedAt: string | null; sale: { invoiceNumber: string; total: string | number }; refundPayment: { method: string; amount: string | number; referenceNumber: string | null } | null; items: Array<{ id: string; quantity: string | number; unitRefund: string | number; condition: string | null; restock: boolean; saleItem: { product: { sku: string; name: string }; inventoryUnit: { serialNumber: string; status: string } | null } }> };
const money = (value: string | number) => new Intl.NumberFormat("en-LK", { style: "currency", currency: "LKR" }).format(Number(value));

export default async function ReturnDetailsPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const value = await serverApi<ReturnDetail>(`/returns/${encodeURIComponent(id)}`);
  return <main className="space-y-6 p-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase text-[#0E9384]">Return details</p><h1 className="text-2xl font-bold">{value.returnNumber}</h1><p className="text-sm text-slate-500">Invoice {value.sale.invoiceNumber} · {new Date(value.createdAt).toLocaleString()}</p></div><Link href="/returns-refunds/history" className="rounded-xl border px-4 py-2 text-sm font-semibold">Back to history</Link></header><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{ label: "Status", value: value.status }, { label: "Resolution", value: value.resolution.replaceAll("_", " ") }, { label: "Refund total", value: money(value.total) }, { label: "Reason", value: value.reason }].map((item) => <article key={item.label} className="rounded-2xl border bg-white p-5"><p className="text-xs uppercase text-slate-500">{item.label}</p><p className="mt-2 font-bold">{item.value}</p></article>)}</section><section className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-5 font-bold">Returned items</div><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">Product</th><th className="p-4">Serial</th><th className="p-4">Quantity</th><th className="p-4">Condition</th><th className="p-4">Restocked</th><th className="p-4">Refund</th></tr></thead><tbody>{value.items.map((item) => <tr key={item.id} className="border-t"><td className="p-4"><b>{item.saleItem.product.name}</b><small className="block text-slate-500">{item.saleItem.product.sku}</small></td><td className="p-4 font-mono text-xs">{item.saleItem.inventoryUnit?.serialNumber ?? "—"}</td><td className="p-4">{Number(item.quantity)}</td><td className="p-4">{item.condition ?? "—"}</td><td className="p-4">{item.restock ? "Yes" : "No"}</td><td className="p-4 font-semibold">{money(Number(item.unitRefund) * Number(item.quantity))}</td></tr>)}</tbody></table></section><section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Resolution record</h2><div className="mt-4 grid gap-4 sm:grid-cols-3"><p><span className="block text-xs text-slate-500">Refund payment</span>{value.refundPayment ? `${value.refundPayment.method} · ${money(value.refundPayment.amount)}` : "—"}</p><p><span className="block text-xs text-slate-500">Store credit</span>{money(value.storeCreditAmount)}</p><p><span className="block text-xs text-slate-500">Loyalty points</span>{value.loyaltyPointsAwarded}</p></div></section></main>;
}
