"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { ArrowLeft, BarChart3, Mail, MessageCircle, Package, Pause, Play, ReceiptText } from "lucide-react";
import { apiGet, apiPatch } from "@/lib/api/client";
import { formatMoney, formatPromotionOffer, type PromotionDetail } from "../promotion-types";

function showDate(value: string | null) { return value ? new Intl.DateTimeFormat("en-LK", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "No limit"; }

export default function PromotionDetailsClientView() {
  const { id } = useParams<{ id: string }>();
  const [promotion, setPromotion] = useState<PromotionDetail | null>(null); const [error, setError] = useState(""); const [updating, setUpdating] = useState(false);
  const load = useCallback(async () => { setError(""); try { setPromotion(await apiGet<PromotionDetail>(`/discounts/${id}`)); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load promotion."); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  async function toggleStatus() { if (!promotion) return; setUpdating(true); setError(""); try { await apiPatch(`/discounts/${id}`, { status: promotion.recordStatus === "ACTIVE" ? "INACTIVE" : "ACTIVE" }); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to update promotion."); } finally { setUpdating(false); } }
  if (!promotion && !error) return <main className="min-h-screen bg-[var(--brand-app-bg)] p-6 text-sm text-slate-500">Loading promotion details…</main>;
  if (!promotion) return <main className="min-h-screen bg-[var(--brand-app-bg)] p-6"><div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-rose-700">{error}</div><Link href="/promotions" className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-[var(--brand-green)]"><ArrowLeft className="h-4 w-4" />Back to promotions</Link></main>;
  const metrics = [{ label: "Redemptions", value: promotion.usageCount.toLocaleString() }, { label: "Sales", value: promotion.salesCount.toLocaleString() }, { label: "Discount given", value: formatMoney(promotion.totalDiscount) }, { label: "Promotion revenue", value: formatMoney(promotion.revenue) }];
  return <main className="min-h-screen space-y-6 bg-[var(--brand-app-bg)] p-6">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><Link href="/promotions" className="mb-2 inline-flex items-center gap-1 text-xs font-semibold text-[var(--brand-green)]"><ArrowLeft className="h-3.5 w-3.5" />Promotions</Link><div className="flex flex-wrap items-center gap-3"><h1 className="text-xl font-bold">{promotion.name}</h1><span className="rounded-full bg-emerald-100 px-2.5 py-1 text-[10px] font-bold text-emerald-700">{promotion.lifecycleStatus}</span></div><p className="mt-1 text-xs text-slate-500">{promotion.code} · {formatPromotionOffer(promotion)}</p></div><div className="flex gap-2"><Link href="/promotions/performance" className="flex h-9 items-center gap-2 rounded-xl border px-4 text-xs font-semibold"><BarChart3 className="h-4 w-4" />Performance</Link>{promotion.recordStatus !== "ARCHIVED" && <button type="button" disabled={updating} onClick={() => void toggleStatus()} className={`flex h-9 items-center gap-2 rounded-xl px-4 text-xs font-bold text-white ${promotion.recordStatus === "ACTIVE" ? "bg-amber-600" : "bg-[var(--brand-green)]"}`}>{promotion.recordStatus === "ACTIVE" ? <Pause className="h-4 w-4" /> : <Play className="h-4 w-4" />}{promotion.recordStatus === "ACTIVE" ? "Pause" : "Resume"}</button>}</div></div>
    {error && <div className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{metrics.map((metric) => <div key={metric.label} className="rounded-2xl border border-[var(--brand-stroke)] bg-white p-5"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">{metric.label}</p><p className="mt-2 text-2xl font-extrabold">{metric.value}</p></div>)}</div>
    <div className="grid gap-6 lg:grid-cols-3"><section className="rounded-2xl border border-[var(--brand-stroke)] bg-white p-6 lg:col-span-2"><h2 className="font-bold">Campaign configuration</h2><p className="mt-2 text-sm text-slate-600">{promotion.description || "No customer-facing description was added."}</p><dl className="mt-6 grid gap-5 text-sm sm:grid-cols-2"><div><dt className="text-xs text-slate-500">Applies to</dt><dd className="mt-1 font-semibold">{promotion.product ? `${promotion.product.sku} · ${promotion.product.name}` : "All products"}</dd></div><div><dt className="text-xs text-slate-500">Quantity rule</dt><dd className="mt-1 font-semibold">Minimum {promotion.minimumQuantity}{promotion.maximumQuantity ? `, maximum ${promotion.maximumQuantity}` : ", no maximum"}</dd></div><div><dt className="text-xs text-slate-500">Starts</dt><dd className="mt-1 font-semibold">{showDate(promotion.startsAt)}</dd></div><div><dt className="text-xs text-slate-500">Ends</dt><dd className="mt-1 font-semibold">{showDate(promotion.endsAt)}</dd></div><div><dt className="text-xs text-slate-500">Priority</dt><dd className="mt-1 font-semibold">{promotion.priority}</dd></div><div><dt className="text-xs text-slate-500">Units sold with offer</dt><dd className="mt-1 font-semibold">{promotion.unitsSold}</dd></div></dl></section>
      <section className="rounded-2xl border border-[var(--brand-stroke)] bg-white p-6"><h2 className="font-bold">Customer announcement</h2><div className="mt-5 space-y-3"><div className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><Mail className="h-5 w-5 text-[var(--brand-green)]" /><span className="text-sm"><strong className="block">Email</strong>{promotion.notifyEmail ? "Enabled" : "Disabled"}</span></div><div className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><MessageCircle className="h-5 w-5 text-[var(--brand-green)]" /><span className="text-sm"><strong className="block">WhatsApp</strong>{promotion.notifyWhatsapp ? "Enabled" : "Disabled"}</span></div><div className="rounded-xl border border-dashed p-3 text-xs text-slate-500">{promotion.promotionNotifiedAt ? `Announcement processed ${showDate(promotion.promotionNotifiedAt)}` : promotion.notifyEmail || promotion.notifyWhatsapp ? "Will be processed when the promotion starts." : "No announcement selected."}</div></div></section></div>
    <section className="overflow-hidden rounded-2xl border border-[var(--brand-stroke)] bg-white"><div className="flex items-center gap-2 border-b p-5"><ReceiptText className="h-5 w-5 text-[var(--brand-green)]" /><h2 className="font-bold">Recent redemptions</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-5 py-3">Invoice</th><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Date</th><th className="px-5 py-3">Discount</th></tr></thead><tbody className="divide-y">{promotion.recentActivity.map((item) => <tr key={item.id}><td className="px-5 py-3 font-semibold">{item.sale.invoiceNumber}</td><td className="px-5 py-3">{item.sale.customer ? `${item.sale.customer.firstName} ${item.sale.customer.lastName}` : "Walk-in customer"}</td><td className="px-5 py-3">{showDate(item.sale.createdAt)}</td><td className="px-5 py-3 font-semibold">{formatMoney(item.amount)}</td></tr>)}{!promotion.recentActivity.length && <tr><td colSpan={4} className="px-5 py-10 text-center text-slate-500"><Package className="mx-auto mb-2 h-6 w-6" />No recorded redemptions yet.</td></tr>}</tbody></table></div></section>
  </main>;
}
