"use client";

import { useCallback, useEffect, useState } from "react";
import { ChevronDown, ChevronUp, RefreshCw, Wifi, WifiOff } from "lucide-react";
import { apiGet, apiPost } from "@/lib/api/client";
import { useOfflineMode } from "@/components/dashboard/pos/OfflineContext";

type Operation = { id: string; clientOperationId: string; operationType: string; status: string; errorCode: string | null; errorMessage: string | null; response: unknown };
type Batch = { id: string; clientBatchId: string; deviceId: string; status: string; receivedAt: string; operations: Operation[] };
type Result = { data: Batch[]; meta: { page: number; total: number; pageCount: number } };

export default function OfflineSyncPage() {
  const { isOffline, isChecking, retryConnection } = useOfflineMode();
  const [result, setResult] = useState<Result>({ data: [], meta: { page: 1, total: 0, pageCount: 0 } });
  const [page, setPage] = useState(1), [loading, setLoading] = useState(true), [queued, setQueued] = useState(0), [expanded, setExpanded] = useState(""), [message, setMessage] = useState("");
  const load = useCallback((target = page) => { setLoading(true); apiGet<Result>(`/offline-sync/batches?page=${target}&pageSize=20`).then(setResult).catch((error) => setMessage(error instanceof Error ? error.message : "Unable to load batches.")).finally(() => setLoading(false)); }, [page]);
  useEffect(() => { load(page); setQueued((JSON.parse(localStorage.getItem("technova_pos_queue") ?? "[]") as unknown[]).length); }, [load, page]);
  async function inspect(batch: Batch) { if (expanded === batch.id) return setExpanded(""); const detail = await apiGet<Batch>(`/offline-sync/batches/${batch.id}`); setResult((current) => ({ ...current, data: current.data.map((row) => row.id === detail.id ? detail : row) })); setExpanded(batch.id); }
  async function synchronize() { const operations = JSON.parse(localStorage.getItem("technova_pos_queue") ?? "[]") as unknown[]; if (!operations.length) return; let deviceId = localStorage.getItem("technova_device_id"); if (!deviceId) { deviceId = `web-${crypto.randomUUID()}`; localStorage.setItem("technova_device_id", deviceId); } try { await apiPost("/offline-sync/batches", { clientBatchId: crypto.randomUUID(), deviceId, operations }); localStorage.removeItem("technova_pos_queue"); setQueued(0); setPage(1); load(1); } catch (error) { setMessage(error instanceof Error ? error.message : "Synchronization failed."); } }
  return <main className="space-y-6 p-6">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase text-[#0E9384]">Resilient POS</p><h1 className="text-2xl font-bold">Offline Synchronization</h1><p className="text-sm text-slate-500">Inspect every applied or rejected offline operation.</p></div><div className="flex gap-2">{queued > 0 && <button onClick={synchronize} disabled={isOffline} className="rounded-xl bg-[#0E9384] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Synchronize {queued}</button>}<button onClick={async () => { await retryConnection(); load(); }} disabled={isChecking} className="flex items-center gap-2 rounded-xl border px-4 py-2 text-sm font-semibold"><RefreshCw className={`h-4 w-4 ${isChecking ? "animate-spin" : ""}`} />Refresh</button></div></header>
    {message && <p className="rounded-xl bg-amber-50 p-3 text-sm text-amber-800">{message}</p>}
    <div className={`flex items-center gap-3 rounded-2xl border p-4 ${isOffline ? "bg-amber-50 text-amber-800" : "bg-emerald-50 text-emerald-800"}`}>{isOffline ? <WifiOff /> : <Wifi />}<div><p className="font-semibold">{isOffline ? "This device is offline" : "Connected to TechNova API"}</p><p className="text-xs">{queued} queued operations on this device.</p></div></div>
    <section className="overflow-hidden rounded-2xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Received</th><th className="p-4">Device</th><th className="p-4">Batch</th><th className="p-4">Operations</th><th className="p-4">Status</th><th /></tr></thead><tbody>{result.data.map((batch) => <BatchRows key={batch.id} batch={batch} open={expanded === batch.id} onToggle={() => void inspect(batch)} />)}</tbody></table>{loading && <p className="p-8 text-center">Loading…</p>}{!loading && !result.data.length && <p className="p-8 text-center text-sm text-slate-500">No batches yet.</p>}<div className="flex justify-between border-t p-4 text-sm"><span>{result.meta.total} batches</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)} className="rounded-lg border px-3 py-1 disabled:opacity-40">Previous</button><span>{page} / {Math.max(1, result.meta.pageCount)}</span><button disabled={page >= result.meta.pageCount} onClick={() => setPage((value) => value + 1)} className="rounded-lg border px-3 py-1 disabled:opacity-40">Next</button></div></div></section>
  </main>;
}

function BatchRows({ batch, open, onToggle }: { batch: Batch; open: boolean; onToggle: () => void }) {
  return <><tr className="border-t"><td className="p-4">{new Date(batch.receivedAt).toLocaleString()}</td><td className="p-4">{batch.deviceId}</td><td className="p-4 font-mono text-xs">{batch.clientBatchId}</td><td className="p-4">{batch.operations.length}</td><td className="p-4 font-semibold">{batch.status.replaceAll("_", " ")}</td><td className="p-4"><button onClick={onToggle} className="text-[#0E9384]">{open ? <ChevronUp /> : <ChevronDown />}</button></td></tr>{open && <tr><td colSpan={6} className="bg-slate-50 p-5"><div className="space-y-3">{batch.operations.map((operation) => <article key={operation.id} className="rounded-xl border bg-white p-4"><div className="flex justify-between"><div><p className="font-semibold">{operation.operationType}</p><p className="font-mono text-xs text-slate-500">{operation.clientOperationId}</p></div><strong className={operation.status === "APPLIED" ? "text-emerald-700" : "text-rose-700"}>{operation.status}</strong></div>{operation.errorMessage && <p className="mt-3 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{operation.errorCode}: {operation.errorMessage}</p>}{operation.response != null && <pre className="mt-3 max-h-40 overflow-auto rounded-lg bg-slate-950 p-3 text-xs text-white">{JSON.stringify(operation.response, null, 2)}</pre>}</article>)}</div></td></tr>}</>;
}
