import Link from "next/link";
import { serverApi } from "@/lib/api/server";

type Sale = { invoiceNumber: string; status: string; subtotal: string | number; discountTotal: string | number; taxTotal: string | number; total: string | number; paidTotal: string | number; balanceDue: string | number; branch: { name: string }; customer: { firstName: string; lastName: string | null } | null; items: Array<{ id: string; quantity: string | number; unitPrice: string | number; discountTotal: string | number; lineTotal: string | number; product: { sku: string; name: string }; inventoryUnit: { serialNumber: string } | null }>; payments: Array<{ id: string; method: string; amount: string | number }>; receipt: { receiptNumber: string } | null };

export default async function SaleDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const sale = await serverApi<Sale>(`/sales/${id}`);
  return <main className="space-y-6 p-6"><div className="flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-[#0E9384]">{sale.receipt?.receiptNumber ?? "Sale"}</p><h1 className="text-2xl font-bold">{sale.invoiceNumber}</h1><p className="text-sm text-slate-500">{sale.branch.name} · {sale.customer ? `${sale.customer.firstName} ${sale.customer.lastName ?? ""}` : "Walk-in"}</p></div><Link href="/sales" className="rounded-xl border px-4 py-2 text-sm font-semibold">Back</Link></div><section className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="px-4 py-3">Product</th><th className="px-4 py-3">Serial</th><th className="px-4 py-3">Qty</th><th className="px-4 py-3">Price</th><th className="px-4 py-3">Discount</th><th className="px-4 py-3">Total</th></tr></thead><tbody className="divide-y">{sale.items.map((item) => <tr key={item.id}><td className="px-4 py-3">{item.product.name}<p className="text-xs text-slate-500">{item.product.sku}</p></td><td className="px-4 py-3 font-mono text-xs">{item.inventoryUnit?.serialNumber ?? "—"}</td><td className="px-4 py-3">{Number(item.quantity)}</td><td className="px-4 py-3">{Number(item.unitPrice).toLocaleString()}</td><td className="px-4 py-3">{Number(item.discountTotal).toLocaleString()}</td><td className="px-4 py-3 font-semibold">{Number(item.lineTotal).toLocaleString()}</td></tr>)}</tbody></table></section><div className="grid gap-4 md:grid-cols-2"><section className="rounded-2xl border bg-white p-5"><h2 className="mb-3 font-bold">Payments</h2>{sale.payments.map((payment) => <div key={payment.id} className="flex justify-between border-b py-2 text-sm"><span>{payment.method.replaceAll("_", " ")}</span><span>{Number(payment.amount).toLocaleString()}</span></div>)}</section><section className="space-y-2 rounded-2xl border bg-white p-5 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{Number(sale.subtotal).toLocaleString()}</span></div><div className="flex justify-between text-emerald-700"><span>Discount</span><span>-{Number(sale.discountTotal).toLocaleString()}</span></div><div className="flex justify-between"><span>Tax</span><span>{Number(sale.taxTotal).toLocaleString()}</span></div><div className="flex justify-between border-t pt-3 text-lg font-bold"><span>Total</span><span>{Number(sale.total).toLocaleString()}</span></div><div className="flex justify-between text-rose-600"><span>Balance due</span><span>{Number(sale.balanceDue).toLocaleString()}</span></div></section></div></main>;
}
