"use client";
import { useEffect, useRef, useState } from "react";
import { Camera, X } from "lucide-react";
type Detection = { rawValue: string }; type Detector = { detect(source: HTMLVideoElement): Promise<Detection[]> }; type DetectorConstructor = new (options?: { formats?: string[] }) => Detector;
export default function BarcodeScannerButton({ onScan }: { onScan(value: string): void }) {
  const [open, setOpen] = useState(false), [error, setError] = useState<string | null>(null);
  const videoRef = useRef<HTMLVideoElement>(null), streamRef = useRef<MediaStream | null>(null), frameRef = useRef<number | null>(null);
  function stop() { if (frameRef.current) cancelAnimationFrame(frameRef.current); streamRef.current?.getTracks().forEach((track) => track.stop()); streamRef.current = null; frameRef.current = null; setOpen(false); }
  useEffect(() => () => { streamRef.current?.getTracks().forEach((track) => track.stop()); if (frameRef.current) cancelAnimationFrame(frameRef.current); }, []);
  async function start() { setError(null); setOpen(true); const DetectorClass = (window as unknown as { BarcodeDetector?: DetectorConstructor }).BarcodeDetector; if (!DetectorClass) { setError("Camera scanning needs Chrome or Edge over HTTPS. You can still enter the barcode manually."); return; } try { const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: "environment" } }, audio: false }); streamRef.current = stream; const video = videoRef.current; if (!video) return; video.srcObject = stream; await video.play(); const detector = new DetectorClass({ formats: ["ean_13", "ean_8", "code_128", "code_39", "upc_a", "upc_e", "qr_code"] }); const scan = async () => { if (!streamRef.current) return; try { const result = await detector.detect(video); if (result[0]?.rawValue) { onScan(result[0].rawValue); stop(); return; } } catch {} frameRef.current = requestAnimationFrame(() => void scan()); }; void scan(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Camera permission was denied."); } }
  return <><button type="button" onClick={() => void start()} className="mt-1 inline-flex h-10 shrink-0 items-center gap-2 rounded-xl border border-[#0E9384] bg-teal-50 px-3 text-xs font-semibold text-[#0E9384]"><Camera className="h-4 w-4"/>Scan</button>{open && <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/70 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold">Scan product barcode</h2><p className="text-xs text-slate-500">Place the barcode inside the camera view.</p></div><button type="button" onClick={stop} className="rounded-lg p-2 hover:bg-slate-100"><X className="h-5 w-5"/></button></div><video ref={videoRef} playsInline muted className="aspect-video w-full rounded-xl bg-slate-950 object-cover"/>{error && <p className="mt-3 rounded-lg bg-amber-50 p-3 text-xs text-amber-800">{error}</p>}</div></div>}</>;
}
