"use client";
import { useState } from "react";
import Link from "next/link";
import { Check, Circle, PackageCheck, Send } from "lucide-react";
import { apiGet, apiPost } from "@/lib/api/client";
import { useBranch } from "@/components/dashboard/BranchContext";
export type TransferDetailData = { id: string; transferNumber: string; status: string; notes: string | null; createdAt: string; dispatchedAt: string | null; receivedAt: string | null; sourceBranchId: string; destinationBranchId: string; sourceBranch: { id: string; name: string }; destinationBranch: { id: string; name: string }; items: Array<{ id: string; productId: string; quantity: string | number; receivedQuantity: string | number; product: { sku: string; name: string; trackSerials: boolean } }> };
const stages = ["SUBMITTED", "IN_TRANSIT", "RECEIVED"];
export default function TransferDetail({ initial }: { initial: TransferDetailData }) {
  const { branchId } = useBranch();
  const [transfer, setTransfer] = useState(initial), [serials, setSerials] = useState<Record<string, string>>({}), [message, setMessage] = useState<string | null>(null), [working, setWorking] = useState(false);
  const isSource = branchId === transfer.sourceBranchId, isDestination = branchId === transfer.destinationBranchId;
  const serializedItems = () => transfer.items.filter((item) => item.product.trackSerials).map((item) => ({ productId: item.productId, serialNumbers: (serials[item.id] ?? "").split(/[\n,]/).map((value) => value.trim()).filter(Boolean) }));
  async function refresh() { setTransfer(await apiGet<TransferDetailData>(`/inventory/transfers/${transfer.id}`)); }
  async function dispatch() { setWorking(true); try { await apiPost(`/inventory/transfers/${transfer.id}/dispatch`, { serializedItems: serializedItems() }); await refresh(); setMessage("Goods dispatched. Source stock was deducted and the destination can now receive it."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to dispatch transfer."); } finally { setWorking(false); } }
  async function receive() { setWorking(true); try { await apiPost(`/inventory/transfers/${transfer.id}/receive`, {}); await refresh(); setMessage("Transfer received. Accepted stock is now available at the destination branch."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to receive transfer."); } finally { setWorking(false); } }
  async function directReceive() { if (!window.confirm("Confirm that the destination physically received these goods? Source stock will be deducted and destination stock added immediately.")) return; setWorking(true); try { await apiPost(`/inventory/transfers/${transfer.id}/dispatch`, { serializedItems: serializedItems() }); await apiPost(`/inventory/transfers/${transfer.id}/receive`, {}); await refresh(); setMessage("Direct handover completed. Both dispatch and receipt were recorded in the audit and movement history."); } catch (error) { await refresh().catch(() => undefined); setMessage(error instanceof Error ? error.message : "Unable to complete direct receipt."); } finally { setWorking(false); } }
  const currentIndex = transfer.status === "DRAFT" ? -1 : stages.indexOf(transfer.status);
  return <main className="space-y-5 bg-[#F8FAFC] p-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase text-[#0E9384]">Stock transfer</p><h1 className="text-2xl font-bold">{transfer.transferNumber}</h1><p className="text-sm text-slate-500">{transfer.sourceBranch.name} → {transfer.destinationBranch.name}</p></div><Link href="/inventory/transfer" className="rounded-xl border bg-white px-4 py-2 text-sm font-semibold">Back to transfers</Link></div>{message && <div className="rounded-xl border border-teal-200 bg-teal-50 p-3 text-sm text-teal-800">{message}</div>}
    <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Transfer lifecycle</h2><div className="mt-5 grid gap-3 sm:grid-cols-3">{stages.map((stage, index) => { const complete = currentIndex >= index; const date = stage === "SUBMITTED" ? transfer.createdAt : stage === "IN_TRANSIT" ? transfer.dispatchedAt : transfer.receivedAt; return <article key={stage} className={`rounded-xl border p-4 ${complete ? "border-teal-200 bg-teal-50" : "bg-slate-50"}`}><div className="flex items-center gap-2">{complete ? <Check className="h-5 w-5 rounded-full bg-[#0E9384] p-1 text-white"/> : <Circle className="h-5 w-5 text-slate-300"/>}<p className="text-sm font-bold">{stage === "SUBMITTED" ? "Created / submitted" : stage.replaceAll("_", " ")}</p></div><p className="mt-2 text-xs text-slate-500">{date ? new Date(date).toLocaleString() : stage === "IN_TRANSIT" ? "Waiting for source dispatch" : "Waiting for destination confirmation"}</p></article>; })}</div></section>
    <div className="grid gap-5 xl:grid-cols-[1fr_330px]"><section className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-5"><h2 className="font-bold">Transfer items</h2><p className="text-xs text-slate-500">Verify quantities and serialized units before changing status.</p></div><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Product</th><th className="p-4">Expected</th><th className="p-4">Received</th><th className="p-4">State</th></tr></thead><tbody>{transfer.items.map((item) => <tr key={item.id} className="border-t"><td className="p-4"><p className="font-semibold">{item.product.name}</p><p className="text-xs text-slate-500">{item.product.sku}{item.product.trackSerials ? " · Serialized" : ""}</p>{transfer.status === "SUBMITTED" && item.product.trackSerials && <label className="mt-3 block text-xs font-semibold">Serial numbers ({Number(item.quantity)} required)<textarea value={serials[item.id] ?? ""} onChange={(event) => setSerials({ ...serials, [item.id]: event.target.value })} className="mt-1 min-h-20 w-full rounded-xl border p-3 text-sm" placeholder="One serial number per line"/></label>}</td><td className="p-4">{Number(item.quantity)}</td><td className="p-4">{Number(item.receivedQuantity)}</td><td className="p-4"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold">{transfer.status === "RECEIVED" ? "At destination" : transfer.status === "IN_TRANSIT" ? "In transit" : "At source"}</span></td></tr>)}</tbody></table></section>
      <aside className="h-fit space-y-4 rounded-2xl border bg-white p-5"><div><h2 className="font-bold">Verification actions</h2><p className="text-xs text-slate-500">Current selected branch: {isSource ? transfer.sourceBranch.name : isDestination ? transfer.destinationBranch.name : "another branch"}</p></div>{transfer.status === "SUBMITTED" && isSource && <button disabled={working} onClick={() => void dispatch()} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#0E9384] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40"><Send className="h-4 w-4"/>Mark as dispatched</button>}{transfer.status === "SUBMITTED" && isDestination && <button disabled={working} onClick={() => void directReceive()} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#0E9384] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40"><PackageCheck className="h-4 w-4"/>Dispatch & receive directly</button>}{transfer.status === "IN_TRANSIT" && isDestination && <button disabled={working} onClick={() => void receive()} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#0E9384] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40"><PackageCheck className="h-4 w-4"/>Confirm goods received</button>}{transfer.status === "IN_TRANSIT" && isSource && <p className="rounded-xl bg-blue-50 p-3 text-xs text-blue-700">Goods are in transit. The destination branch must confirm receipt.</p>}{transfer.status === "RECEIVED" && <p className="rounded-xl bg-emerald-50 p-3 text-xs text-emerald-700">Completed. Destination inventory and movement history have been updated.</p>}{!isSource && !isDestination && <p className="rounded-xl bg-amber-50 p-3 text-xs text-amber-800">Select the source or destination branch in the top navigation to perform transfer actions.</p>}{transfer.notes && <div className="border-t pt-4"><p className="text-xs font-semibold">Transfer reason</p><p className="mt-1 text-sm text-slate-600">{transfer.notes}</p></div>}</aside></div>
  </main>;
}
